apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Install ArgoCD Image Updater from upstream GitHub repo
  - https://github.com/argoproj-labs/argocd-image-updater//config/default?ref=v1.0.2
  # Harbor registry credentials secret
  - argocd-image-updater-secret.yaml
  # ImageUpdater CR for demo app
  - image-updater-demo-app.yaml
