apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3IubG9jYWwiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiSGFyYm9yMTIzNDUiLCJlbWFpbCI6InVudXNlZEBleGFtcGxlLmNvbSIsImF1dGgiOiJZV1J0YVc0NlNHRnlZbTl5TVRJek5EVT0ifX19
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: https://harbor.local
  name: harbor-registry
  namespace: tekton-pipelines
type: kubernetes.io/dockerconfigjson
