kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: test-cluster-1
networking:
  disableDefaultCNI: true   # Important for Cilium
  kubeProxyMode: "none" # set to none
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
    image: kindest/node:v1.33.0
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "127.0.0.1"
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "127.0.0.1"

  - role: worker
    image: kindest/node:v1.33.0

  - role: worker
    image: kindest/node:v1.33.0
  
    