apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Prometheus monitoring stack

  sourceRepos:
    - harbor.local
    - harbor.local/helm

  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: prometheus-admin
      description: Full access for prometheus admins
      policies:
        - p, proj:prometheus-project:prometheus-admin, applications, *, prometheus-project/*, allow
