apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prometheus-project
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Prometheus monitoring stack
# Define the source repositories that applications in this project can use
  sourceRepos:
    - harbor.local
    - harbor.local/helm
# Define the cluster and namespaces where applications in this project can be deployed
  destinations:
    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  roles:
    - name: prometheus-admin
      description: Full access for prometheus admins
      policies:
        - p, proj:prometheus-project:prometheus-admin, applications, *, prometheus-project/*, allow
