apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tekton
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tekton-project

  source:
    repoURL: harbor.local
    chart: helm/tekton-pipelines
    targetRevision: 1.9.0
    helm:
      values: |
        config:
          feature-flags:
            set-security-context: "true"

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
