apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tekton-pipelines
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: tekton
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tekton-project

  source:
    repoURL: https://github.com/emilpeychev/kind-cluster-cilium.git
    targetRevision: HEAD
    path: Tekton/manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: tekton-pipelines

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
