apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  labels:
    app.kubernetes.io/part-of: security
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kyverno-project
  source:
    repoURL: harbor.local
    chart: helm/kyverno
    targetRevision: 3.7.0
    helm:
      values: |
        admissionController:
          replicas: 1
          metricsService:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8000"
              prometheus.io/path: "/metrics"
        backgroundController:
          replicas: 1
          metricsService:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8000"
              prometheus.io/path: "/metrics"
        cleanupController:
          replicas: 1
          metricsService:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8000"
              prometheus.io/path: "/metrics"
        reportsController:
          replicas: 1
          metricsService:
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "8000"
              prometheus.io/path: "/metrics"
        config:
          preserve: false
        features:
          policyExceptions:
            enabled: true
          registryClient:
            allowInsecure: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/labels
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/creationTimestamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
