apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app1
  namespace: demo-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app1
  template:
    metadata:
      labels:
        app: demo-app1
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: app
          image: harbor-registry.harbor.svc.cluster.local:5000/library/demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
