apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: demo-app1
  namespace: demo-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app1
  template:
    metadata:
      labels:
        app: demo-app1
      annotations:
<<<<<<< HEAD
        kubectl.kubernetes.io/restartedAt: "2026-01-20T08:02:58Z"
=======
        kubectl.kubernetes.io/restartedAt: "placeholder"
>>>>>>> 6f30c09 (bg color)
        git.commit-sha: "placeholder-sha"
    spec:
      imagePullSecrets:
        - name: harbor-regcred
      containers:
        - name: app
<<<<<<< HEAD
          image: harbor.local/library/demo-app:20260120-080235
=======
          image: harbor.local/library/demo-app:latest
>>>>>>> 6f30c09 (bg color)
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
