apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- httproute.yaml

images:
- name: harbor.local/library/demo-app
<<<<<<< HEAD
  newTag: 20260120-080235
=======
  newTag: latest
>>>>>>> 6f30c09 (bg color)
