apiVersion: v1
kind: Service
metadata:
  annotations:
    labels:
      app.kubernetes.io/part-of: demo-apps
  name: demo-app1
  namespace: demo-apps
spec:
  selector:
    app: demo-app1
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
