apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
  annotations:
    # add image updater annotation to track image updates
    argocd-image-updater.argoproj.io/image-list: "harbor.local/library/demo-app:~0.1"
    argocd.argoproj.io/sync-wave: "2"
  # add finalizer to clean up applications when deleting the ApplicationSet
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - name: demo-apps
            path: ArgoCD-demo-apps/apps
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: demo-apps
      source:
        repoURL: git@github.com:emilpeychev/kind-cluster-cilium.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
