apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: demo-apps
            path: ArgoCD-demo-apps/apps
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd-image-updater.argoproj.io/image-list: demo=harbor.local/library/demo-app
        argocd-image-updater.argoproj.io/demo.update-strategy: newest-build
        argocd-image-updater.argoproj.io/demo.pull-secret: pullsecret:argocd/harbor-registry-creds
    spec:
      project: demo-apps
      source:
        repoURL: git@github.com:emilpeychev/kind-cluster-cilium.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
