apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - name: demo-apps
            path: ArgoCD-demo-apps/apps
  template:
    metadata:
      name: '{{name}}'
      annotations:
        # ArgoCD Image Updater - auto-update on new image push
        argocd-image-updater.argoproj.io/image-list: app=harbor.local/library/demo-app:~.*
        argocd-image-updater.argoproj.io/app.update-strategy: digest
        argocd-image-updater.argoproj.io/write-back-method: argocd
    spec:
      project: demo-apps
      source:
        repoURL: git@github.com:emilpeychev/kind-cluster-cilium.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
