apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-apps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: demo-app=harbor.local/library/demo-app
    argocd-image-updater.argoproj.io/demo-app.allow-tags: regexp:^v[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/demo-app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh
    argocd-image-updater.argoproj.io/git-branch: master
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - name: demo-apps
            path: ArgoCD-demo-apps/apps
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: demo-apps
      source:
        repoURL: git@github.com:emilpeychev/kind-cluster-cilium.git
        targetRevision: master
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
